[book]
title = "wtf-go documentation"
authors = ["Laurent VERDO√èA"]
language = "en"

[output.html]
git-repository-url = "https://git.sr.ht/~lvjp/wtf-go"
edit-url-template = "https://git.sr.ht/~lvjp/wtf-go/tree/main/item/docs/src/{{ . }}"
source-url-template = "https://git.sr.ht/~lvjp/wtf-go/tree/main/item/docs/src/{{ .Path }}#L{{ .Start }}-{{ .End }}"
