---
name: "GitHub Pages"

on:
  push:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-24.04

    permissions:
      contents: read # to checkout the source code
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    steps:
      - name: Install latest mdBook
        run: |
          url=$(curl -sSL "https://api.github.com/repos/rust-lang/mdbook/releases/tags/${MDBOOK_VERSION}" | jq -r '.assets[] | select(.name | endswith("x86_64-unknown-linux-gnu.tar.gz")) | .browser_download_url')
          mkdir "${RUNNER_TEMP}/mdbook"
          curl -sSL "${url}" | tar -xz --directory "${RUNNER_TEMP}/mdbook"
          echo "${RUNNER_TEMP}/mdbook" >> "${GITHUB_PATH}"
        env:
          MDBOOK_VERSION: v0.5.2 # renovate dependency

      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build the book
        run: mdbook build
        working-directory: ./docs

      - name: Generate GitHub Pages artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: ./docs/book

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
